apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: ifilyaninitmo/itdt-contained-frontend:master
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_USERNAME
          value: "kkolyambuss"
        - name: REACT_APP_COMPANY_NAME
          value: "home"

---

apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
